### ISSUE TITLE
[Unknown process name] CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

### ISSUE THREAD

**Issue by dqb101140127** [pujiaxin33/JXPatternLock#1]
[Unknown process name] CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by pujiaxin33** [comment]
谢谢反馈🤝 已修复
