### ISSUE TITLE
设置密码时怎样保留第二次显示不消失呢?

### ISSUE THREAD

**Issue by GarkiOS** [pujiaxin33/JXPatternLock#4]
可以考虑提供一个属性默认设置完是隐藏,需要时打开.目前没有找到这个. 如有还请告知. 谢谢

**Comment by pujiaxin33** [comment]
没有你想要的属性，但是你可以自己记录链接的grid，然后把grids数组来调用pathView.addGrid(at: grid.matrix)，相当于代码重新自动连接一次。
